import { StudentProfile, StudyGroup, ChatMessage } from '@/types';

export const CURRENT_USER: StudentProfile = {
  id: 'usr_me_pilot',
  fullName: 'Aoba Student',
  email: 'student@students.aobajapan.jp',
  schoolDomain: 'students.aobajapan.jp',
  schoolName: 'Aoba-Japan International School',
  gradeLevel: 11,
  curriculum: 'IB',
  subjects: ['Math Analysis & Approaches HL', 'Physics HL', 'Economics HL'],
  casHours: 14.5,
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
  role: 'student',
};

export const INITIAL_STUDENTS: Record<string, StudentProfile> = {
  usr_1: {
    id: 'usr_1',
    fullName: 'Maya S.',
    email: 'm.sato@asij.ac.jp',
    schoolDomain: 'asij.ac.jp',
    schoolName: 'American School in Japan',
    gradeLevel: 12,
    curriculum: 'AP',
    subjects: ['AP Calculus BC', 'AP Physics C: Mechanics', 'AP Chemistry'],
    casHours: 28,
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&auto=format&fit=crop&q=80',
  },
  usr_2: {
    id: 'usr_2',
    fullName: 'Liam K.',
    email: 'liam.kim@k-international.ed.jp',
    schoolDomain: 'k-international.ed.jp',
    schoolName: 'K. International School Tokyo',
    gradeLevel: 11,
    curriculum: 'IB',
    subjects: ['Physics HL', 'Chemistry HL', 'Math Analysis & Approaches HL'],
    casHours: 19,
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=120&auto=format&fit=crop&q=80',
  },
  usr_3: {
    id: 'usr_3',
    fullName: 'Aoi M.',
    email: 'aoi.m@issh.ac.jp',
    schoolDomain: 'issh.ac.jp',
    schoolName: 'Intl School of the Sacred Heart',
    gradeLevel: 12,
    curriculum: 'IB',
    subjects: ['Economics HL', 'History HL', 'English A: Literature HL'],
    casHours: 35,
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=120&auto=format&fit=crop&q=80',
  },
  usr_4: {
    id: 'usr_4',
    fullName: 'Ethan R.',
    email: 'ethan.r@smis.ac.jp',
    schoolDomain: 'smis.ac.jp',
    schoolName: "St. Mary's International School",
    gradeLevel: 11,
    curriculum: 'SAT_ACT',
    subjects: ['Digital SAT Math (Advanced & Desmos)', 'Digital SAT Reading & Writing'],
    casHours: 12,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
  },
  usr_5: {
    id: 'usr_5',
    fullName: 'Hana W.',
    email: 'hana.watanabe@bst.ac.jp',
    schoolDomain: 'bst.ac.jp',
    schoolName: 'The British School in Tokyo',
    gradeLevel: 10,
    curriculum: 'IGCSE',
    subjects: ['IGCSE Extended Mathematics', 'IGCSE Physics (0625)'],
    casHours: 8,
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
  },
};

export const INITIAL_GROUPS: StudyGroup[] = [
  {
    id: 'grp_1',
    title: 'May 2024 Math AA HL TZ2 Paper 1 Full Sprint',
    description: 'Doing a timed 90-minute run under exam conditions, followed by 30 mins comparing solutions for Section B differential equations & vectors.',
    curriculum: 'IB',
    subject: 'Math Analysis & Approaches HL',
    format: 'past_paper_sprint',
    venueType: 'hiroo_metropolitan_library',
    venueLabel: 'Tokyo Metropolitan Central Library (Hiroo)',
    meetingTime: 'Today, 4:30 PM',
    durationMinutes: 120,
    maxMembers: 5,
    host: CURRENT_USER,
    members: [CURRENT_USER, INITIAL_STUDENTS.usr_2],
    status: 'open',
    tags: ['Paper 1', 'No Calculator', 'TZ2 Review'],
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: 'grp_2',
    title: 'AP Calculus BC: Series Convergence & Taylor Polynomials',
    description: 'Working through hardest CollegeBoard Free Response Questions (FRQ 6) for Lagrange error bounds and ratio tests with graph proofs.',
    curriculum: 'AP',
    subject: 'AP Calculus BC',
    format: 'exam_cram',
    venueType: 'virtual_zoom',
    venueLabel: 'Encrypted Video Room (Zoom)',
    meetingTime: 'Tomorrow, 5:00 PM',
    durationMinutes: 90,
    maxMembers: 6,
    host: INITIAL_STUDENTS.usr_1,
    members: [INITIAL_STUDENTS.usr_1, INITIAL_STUDENTS.usr_4],
    status: 'open',
    tags: ['Taylor Series', 'FRQ 6', 'May Exam Cram'],
    createdAt: new Date(Date.now() - 3600000 * 8).toISOString(),
  },
  {
    id: 'grp_3',
    title: 'Physics HL Internal Assessment (IA) Peer Rubric Workshop',
    description: 'Bring your draft methodology and error propagation graphs. We will review rubric criteria B (Inquiry) and D (Evaluation) together.',
    curriculum: 'IB',
    subject: 'Physics HL',
    format: 'ia_workshop',
    venueType: 'school_library',
    venueLabel: 'BST Shibuya Campus Quiet Library',
    meetingTime: 'Friday, 3:45 PM',
    durationMinutes: 60,
    maxMembers: 4,
    host: INITIAL_STUDENTS.usr_2,
    members: [INITIAL_STUDENTS.usr_2, CURRENT_USER, INITIAL_STUDENTS.usr_5],
    status: 'open',
    tags: ['IA Draft', 'Rubric Check', 'Error Analysis'],
    createdAt: new Date(Date.now() - 3600000 * 18).toISOString(),
  },
  {
    id: 'grp_4',
    title: 'Digital SAT Module 2 Hard: Desmos Matrix & Systems Hacks',
    description: 'Speed-running the 10 hardest math questions from Bluebook Test 5 & 6 using Desmos regressions and function intersection shortcuts.',
    curriculum: 'SAT_ACT',
    subject: 'Digital SAT Math (Advanced & Desmos)',
    format: 'past_paper_sprint',
    venueType: 'virtual_discord',
    venueLabel: 'Tokyo Student Audio Room',
    meetingTime: 'Saturday, 10:00 AM',
    durationMinutes: 60,
    maxMembers: 6,
    host: INITIAL_STUDENTS.usr_4,
    members: [INITIAL_STUDENTS.usr_4, INITIAL_STUDENTS.usr_1, CURRENT_USER],
    status: 'open',
    tags: ['750+ Target', 'Desmos Hacks', 'Module 2'],
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
  },
  {
    id: 'grp_5',
    title: 'Economics HL Paper 3 Quantitative Policy Calculations',
    description: 'Practicing micro and macro calculations: Keynesian multiplier, tariff welfare losses, elasticity calculations, and progressive tax brackets.',
    curriculum: 'IB',
    subject: 'Economics HL',
    format: 'past_paper_sprint',
    venueType: 'minato_library',
    venueLabel: 'Minato City Central Library (Mita)',
    meetingTime: 'Sunday, 2:00 PM',
    durationMinutes: 90,
    maxMembers: 5,
    host: INITIAL_STUDENTS.usr_3,
    members: [INITIAL_STUDENTS.usr_3],
    status: 'open',
    tags: ['Paper 3', 'Policy Evaluation', 'Math in Econ'],
    createdAt: new Date(Date.now() - 3600000 * 30).toISOString(),
  },
  {
    id: 'grp_6',
    title: 'Silent 50/10 Pomodoro Chamber (Pre-Mocks Focus)',
    description: 'Camera-on or avatars-on quiet study session with lo-fi stream. Strict no-talking rule; post your hourly targets in the room log.',
    curriculum: 'IB',
    subject: 'Theory of Knowledge (TOK)',
    format: 'silent_pomodoro',
    venueType: 'virtual_zoom',
    venueLabel: 'Encrypted Video Room (Zoom)',
    meetingTime: 'Tonight, 8:00 PM',
    durationMinutes: 120,
    maxMembers: 8,
    host: CURRENT_USER,
    members: [CURRENT_USER, INITIAL_STUDENTS.usr_1, INITIAL_STUDENTS.usr_2, INITIAL_STUDENTS.usr_3],
    status: 'open',
    tags: ['Deep Focus', 'Silent', 'Evening Study'],
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
];

export const INITIAL_CHAT_MESSAGES: Record<string, ChatMessage[]> = {
  grp_1: [
    {
      id: 'msg_1',
      groupId: 'grp_1',
      sender: CURRENT_USER,
      content: 'Hey everyone! I printed copies of the May 2024 TZ2 Paper 1. Meet by the 3rd floor study tables in Hiroo Library.',
      createdAt: new Date(Date.now() - 1800000 * 3).toISOString(),
    },
    {
      id: 'msg_2',
      groupId: 'grp_1',
      sender: INITIAL_STUDENTS.usr_2,
      content: 'Awesome Kenji. Did you check question 9 on the vectors with the scalar product? That one was brutal in the mock.',
      createdAt: new Date(Date.now() - 1800000 * 2).toISOString(),
    },
    {
      id: 'msg_3',
      groupId: 'grp_1',
      sender: CURRENT_USER,
      content: 'Yeah exactly, we will spend 20 minutes specifically dissecting the markscheme for that question.',
      createdAt: new Date(Date.now() - 1800000 * 1).toISOString(),
    },
  ],
  grp_2: [
    {
      id: 'msg_4',
      groupId: 'grp_2',
      sender: INITIAL_STUDENTS.usr_1,
      content: 'Zoom link has been generated for tomorrow 5pm. Please make sure you have CollegeBoard FRQ 2021-2023 open on your browser.',
      createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    },
    {
      id: 'msg_5',
      groupId: 'grp_2',
      sender: INITIAL_STUDENTS.usr_4,
      content: 'Got it Maya! Excited to finally get the Lagrange error bound down.',
      createdAt: new Date(Date.now() - 3600000 * 3).toISOString(),
    },
  ],
};
