import {
  SubjectSyllabus,
  Curriculum,
} from '@/types';

export const SYLLABUS_DATA: SubjectSyllabus[] = [
  // ==========================================================================
  // 1. IB DIPLOMA PROGRAMME (Unified SL & HL with dedicated HL Only sections)
  // ==========================================================================
  {
    id: 'ib-math-aa',
    curriculum: 'IB',
    subject: 'Mathematics: Analysis & Approaches',
    icon: 'Calculator',
    hasCalculator: true,
    defaultCalculatorMode: 'graphing',
    topics: [
      {
        id: 'ib-math-aa-t1-core',
        name: 'Topic 1: Number & Algebra (Core SL/HL)',
        subtopics: [
          'Arithmetic and geometric sequences & series',
          'Sum of infinite geometric series and sigma notation',
          'Counting principles: permutations and combinations',
          'Binomial theorem expansion and Pascal triangle',
        ],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-math-aa-t1-hl',
        name: 'Topic 1: Number & Algebra (HL Extension)',
        subtopics: [
          'Complex numbers: Cartesian, polar, and Euler form',
          "De Moivre's theorem and nth roots of unity",
          'Proof by mathematical induction (sums, divisibility, inequalities)',
          'Solutions of systems of linear equations using matrices',
        ],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-math-aa-t2-core',
        name: 'Topic 2: Functions (Core SL/HL)',
        subtopics: [
          'Concept of functions, domain, range, and composite functions',
          'Inverse functions and reflections in y = x',
          'Graph transformations: horizontal/vertical shifts, stretches, reflections',
          'Reciprocal and simple rational functions with vertical/horizontal asymptotes',
        ],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-math-aa-t2-hl',
        name: 'Topic 2: Functions (HL Extension)',
        subtopics: [
          'Polynomial remainder theorem and factor theorem',
          'Rational functions with oblique/slant asymptotes',
          'Odd, even, and self-inverse functions',
          'Modulus functions: equations and inequalities involving |f(x)| and f(|x|)',
        ],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-math-aa-t3-core',
        name: 'Topic 3: Geometry & Trigonometry (Core SL/HL)',
        subtopics: [
          'Radian measure, arc length, and sector area',
          'Unit circle definitions and circular trigonometric functions',
          'Pythagorean, double angle, and reciprocal identities',
          'Trigonometric equations and graphical representations',
        ],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-math-aa-t3-hl',
        name: 'Topic 3: Geometry & Trigonometry (HL Extension)',
        subtopics: [
          'Compound angle, double angle, and symmetrical identity proofs',
          'Vectors in 2D and 3D: dot product, angle between vectors',
          'Vector (cross) product and applications to areas',
          'Vector and Cartesian equations of lines and planes in 3D',
          'Intersections of lines and planes, angle between planes',
        ],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-math-aa-t4-core',
        name: 'Topic 4: Statistics & Probability (Core SL/HL)',
        subtopics: [
          'Concepts of discrete probability, Venn diagrams, tree diagrams',
          'Discrete random variables, expectation E(X), and variance',
          'Binomial distribution B(n, p)',
          'Normal distribution, standardized z-scores, and probability',
        ],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-math-aa-t4-hl',
        name: 'Topic 4: Statistics & Probability (HL Extension)',
        subtopics: [
          'Continuous random variables and probability density functions (PDF)',
          'Poisson distribution Po(m) and mean/variance properties',
          'Hypothesis testing: one-tailed vs two-tailed tests',
          'Type I and Type II errors and critical rejection regions',
        ],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-math-aa-t5-core',
        name: 'Topic 5: Calculus (Core SL/HL)',
        subtopics: [
          'Limits, derivative as rate of change, and tangents/normals',
          'Differentiation rules: power, product, quotient, and chain rule',
          'Second derivatives, concavity, and optimization',
          'Definite and indefinite integrals by inspection and simple substitution',
        ],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-math-aa-t5-hl',
        name: 'Topic 5: Calculus (HL Extension)',
        subtopics: [
          "L'Hopital's rule for indeterminate forms",
          'Implicit differentiation and related rates',
          'Integration techniques: by parts and partial fractions',
          'Volumes of revolution about the x-axis and y-axis',
          'Differential equations: separation of variables & integrating factors',
          'Maclaurin and Taylor series expansions',
        ],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
    ],
  },

  {
    id: 'ib-math-ai',
    curriculum: 'IB',
    subject: 'Mathematics: Applications & Interpretation',
    icon: 'LineChart',
    hasCalculator: true,
    defaultCalculatorMode: 'graphing',
    topics: [
      {
        id: 'ib-math-ai-t1-core',
        name: 'Topic 1: Number and Algebra (Core SL/HL)',
        subtopics: ['Scientific notation, rounding, bounds', 'Arithmetic and geometric sequences & financial apps', 'Systems of linear equations'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-math-ai-t1-hl',
        name: 'Topic 1: Matrices & Eigenvalues (HL Extension)',
        subtopics: ['Matrix multiplication, determinants, and inverses', 'Eigenvalues and eigenvectors', 'Transition matrices and steady-state vectors'],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-math-ai-t2-core',
        name: 'Topic 2: Functions & Modelling (Core SL/HL)',
        subtopics: ['Linear, quadratic, and exponential models', 'Direct and inverse variation', 'Sinusoidal models'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-math-ai-t2-hl',
        name: 'Topic 2: Advanced Modelling (HL Extension)',
        subtopics: ['Logistic models and constraints', 'Piecewise functions', 'Linearizing non-linear data using logarithms'],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-math-ai-t3-core',
        name: 'Topic 3: Geometry and Trigonometry (Core SL/HL)',
        subtopics: ['Right-angled & non-right trigonometry', 'Voronoi diagrams & nearest neighbor interpolation', 'Volumes and surface areas of 3D shapes'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-math-ai-t3-hl',
        name: 'Topic 3: Graph Theory & Kinematics (HL Extension)',
        subtopics: ['Graph theory: vertices, edges, Eulerian and Hamiltonian paths', 'Adjacency matrices and minimum spanning trees', 'Vectors in 2D/3D and spatial transformations'],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-math-ai-t4-core',
        name: 'Topic 4: Statistics and Probability (Core SL/HL)',
        subtopics: ['Descriptive statistics: mean, median, standard deviation', 'Linear correlation and Spearman rank', 'Chi-square test of independence & goodness of fit', 'Normal distribution calculations'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-math-ai-t4-hl',
        name: 'Topic 4: Advanced Inference & Poisson (HL Extension)',
        subtopics: ['Poisson distribution and compound probability', 't-test for independent and paired samples', 'One-way analysis of variance (ANOVA)', 'Confidence intervals and central limit theorem'],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-math-ai-t5-core',
        name: 'Topic 5: Calculus (Core SL/HL)',
        subtopics: ['Derivative rules: power rule, local extrema, optimization', 'Trapezoidal rule for numerical integration', 'Definite integration and area under curves'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-math-ai-t5-hl',
        name: 'Topic 5: Differential Systems & Phase Portraits (HL Extension)',
        subtopics: ['Euler method for coupled first-order systems', 'Coupled linear differential equations', 'Phase portraits, equilibrium points, and stability'],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
    ],
  },

  {
    id: 'ib-physics',
    curriculum: 'IB',
    subject: 'Physics',
    icon: 'Atom',
    hasCalculator: true,
    defaultCalculatorMode: 'scientific',
    topics: [
      {
        id: 'ib-phys-a-core',
        name: 'Theme A: Space, Time, and Motion (Core SL/HL)',
        subtopics: ['Kinematics & projectile motion in 2D', "Forces, friction, and Newton's laws of motion", 'Work, kinetic/potential energy, power, and momentum conservation'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-phys-a-hl',
        name: 'Theme A: Rigid Body Mechanics & Relativity (HL Extension)',
        subtopics: ['Torque, moment of inertia, and rotational dynamics: sum(tau) = I*alpha', 'Angular momentum conservation', 'Galilean and Special Relativity: spacetime, time dilation, length contraction'],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-phys-b-core',
        name: 'Theme B: Particulate Nature of Matter & Gas Laws (Core SL/HL)',
        subtopics: ['Thermal energy transfer: conduction, convection, radiation', 'Specific heat capacity and latent heat', 'Ideal gas equation: PV = nRT and kinetic model'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-phys-b-hl',
        name: 'Theme B: Thermodynamics & Entropy (HL Extension)',
        subtopics: ['First law of thermodynamics: Q = delta U + W', 'Second law of thermodynamics and entropy', 'Heat engines, Carnot cycles, and thermal efficiency'],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-phys-c-core',
        name: 'Theme C: Wave Behaviour & Standing Waves (Core SL/HL)',
        subtopics: ['Simple harmonic motion (SHM) kinematics and energy', 'Wave properties: reflection, refraction, polarization', 'Standing waves on strings and in pipes (harmonics)'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-phys-c-hl',
        name: 'Theme C: Wave Phenomena & Doppler Effect (HL Extension)',
        subtopics: ['Single-slit diffraction intensity & Rayleigh criterion for resolution', 'Interference patterns and thin-film interference', 'Doppler effect for sound and light'],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-phys-d-core',
        name: 'Theme D: Fields & Electric Circuits (Core SL/HL)',
        subtopics: ['Gravitational fields, Newton universal law of gravitation', 'Coulomb law and electric field strength', 'Direct current (DC) circuits, Ohm law, and internal resistance'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-phys-d-hl',
        name: 'Theme D: Electromagnetic Induction & Capacitance (HL Extension)',
        subtopics: ['Magnetic flux, Faraday law, and Lenz law of induction', 'Alternating currents, transformers, and root-mean-square (rms) values', 'Capacitors in circuits: capacitance, dielectric materials, and RC decay'],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-phys-e-core',
        name: 'Theme E: Nuclear Structure & Radioactivity (Core SL/HL)',
        subtopics: ['Atomic energy levels and emission spectra', 'Radioactive decay (alpha, beta, gamma) and half-life', 'Mass defect, binding energy, and nuclear fission/fusion'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-phys-e-hl',
        name: 'Theme E: Quantum Physics & Tunneling (HL Extension)',
        subtopics: ['Photoelectric effect: work function and threshold frequency', 'de Broglie wavelength and wave-particle duality', 'Wavefunctions, probability density, and quantum tunneling'],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
    ],
  },

  {
    id: 'ib-chemistry',
    curriculum: 'IB',
    subject: 'Chemistry',
    icon: 'FlaskConical',
    hasCalculator: true,
    defaultCalculatorMode: 'scientific',
    topics: [
      {
        id: 'ib-chem-s1-core',
        name: 'Structure 1: Particulate Nature & Periodicity (Core SL/HL)',
        subtopics: ['Atomic structure, isotopes, mass spectrometry', 'Electron energy levels and orbital configurations', 'Periodic trends: atomic/ionic radius, ionization energy, electronegativity'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-chem-s1-hl',
        name: 'Structure 1: Transition Elements (HL Extension)',
        subtopics: ['Variable oxidation states and coordination complexes', 'd-orbital splitting and crystal field theory', 'Spectrochemical series and color of transition metal complexes'],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-chem-s2-core',
        name: 'Structure 2: Chemical Bonding Models (Core SL/HL)',
        subtopics: ['Ionic, covalent, and metallic bonding lattices', 'Lewis formulas and VSEPR geometry (linear, trigonal, tetrahedral)', 'Intermolecular forces: London dispersion, dipole-dipole, hydrogen bonding'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-chem-s2-hl',
        name: 'Structure 2: Hybridization & Resonance (HL Extension)',
        subtopics: ['Formal charge determination of stable Lewis structures', 'Resonance and electron delocalization in benzene/carbonate', 'Hybridization: sp, sp2, and sp3 orbitals, sigma and pi bonds'],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-chem-r1-core',
        name: 'Reactivity 1: Energetics & Thermochemistry (Core SL/HL)',
        subtopics: ['Enthalpy of reaction (delta H) and calorimetry', 'Hess law calculations and standard enthalpies of formation', 'Bond enthalpy calculations'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-chem-r1-hl',
        name: 'Reactivity 1: Born-Haber Cycles & Entropy (HL Extension)',
        subtopics: ['Born-Haber cycles and experimental vs theoretical lattice enthalpy', 'Entropy changes (delta S) in chemical reactions', 'Gibbs free energy: delta G = delta H - T*delta S and reaction spontaneity'],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-chem-r2-core',
        name: 'Reactivity 2: Chemical Kinetics (Core SL/HL)',
        subtopics: ['Collision theory, activation energy, and factors affecting rates', 'Maxwell-Boltzmann energy distribution curves', 'Role of homogeneous and heterogeneous catalysts'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-chem-r2-hl',
        name: 'Reactivity 2: Rate Expressions & Mechanisms (HL Extension)',
        subtopics: ['Rate laws, reaction orders, and rate constant k units', 'Reaction mechanisms and rate-determining steps', 'Arrhenius equation: ln(k) vs 1/T activation energy determination'],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-chem-r3-core',
        name: 'Reactivity 3: Equilibrium, Acids & Redox (Core SL/HL)',
        subtopics: ['Equilibrium constant Kc and Le Chatelier principle', 'Brønsted-Lowry acids/bases, pH, Kw, and neutralization', 'Oxidation states, balancing redox reactions, and voltaic cells'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-chem-r3-hl',
        name: 'Reactivity 3: Buffer Systems & Organic Mechanisms (HL Extension)',
        subtopics: ['Calculations with Ka, Kb, pKa, pKb, and pH of weak acids/bases', 'Titration curves, acid-base indicators, and buffer solutions', 'Standard electrode potentials and cell potential: delta G = -nFE', 'Organic substitution (SN1 vs SN2) and electrophilic addition mechanisms'],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
    ],
  },

  {
    id: 'ib-biology',
    curriculum: 'IB',
    subject: 'Biology',
    icon: 'Dna',
    hasCalculator: true,
    defaultCalculatorMode: 'scientific',
    topics: [
      {
        id: 'ib-bio-a-core',
        name: 'Theme A: Unity and Diversity (Core SL/HL)',
        subtopics: ['Cell structure, microscopy, and organelle functions', 'Membrane structure and active/passive transport', 'Cell cycle, mitosis, and stem cell applications'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-bio-a-hl',
        name: 'Theme A: Viruses & Specialization (HL Extension)',
        subtopics: ['Viral structure, diversity, and lytic vs lysogenic cycles', 'Cell differentiation and specialized cellular structures'],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-bio-b-core',
        name: 'Theme B: Form and Function (Core SL/HL)',
        subtopics: ['Carbohydrates, lipids, proteins, and water properties', 'Enzymes: active site, denaturation, and kinetics', 'DNA and RNA structures'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-bio-b-hl',
        name: 'Theme B: Molecular Genetics & Enzymes (HL Extension)',
        subtopics: ['DNA replication with DNA polymerase III, helicase, and RNA primase', 'Transcription, promoter regions, introns/exons, and splicing', 'Translation: ribosome structure, tRNA activation, polysomes', 'Enzyme inhibition (competitive vs non-competitive) and allosteric sites'],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-bio-c-core',
        name: 'Theme C: Interaction and Interdependence (Core SL/HL)',
        subtopics: ['Species, communities, ecosystems, and energy trophic levels', 'Carbon cycling and greenhouse effect', 'Cellular respiration and photosynthesis basics'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-bio-c-hl',
        name: 'Theme C: Cellular Energetics (HL Extension)',
        subtopics: ['Glycolysis, link reaction, Krebs cycle, and oxidative phosphorylation', 'Light-dependent reactions, photolysis, and ATP synthase', 'Light-independent Calvin cycle and RuBisCO carbon fixation'],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-bio-d-core',
        name: 'Theme D: Continuity and Change (Core SL/HL)',
        subtopics: ['Chromosomes, alleles, and mutations', 'Mendelian monohybrid crosses and sex linkage', 'Natural selection and evidence for evolution'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-bio-d-hl',
        name: 'Theme D: Gene Linkage & Animal Physiology (HL Extension)',
        subtopics: ['Meiosis: crossing over, chiasmata, and non-disjunction', 'Gene linkage, dihybrid crosses, and polygenic inheritance', 'Kidney structure and osmoregulation by nephrons', 'Antibody production, clonal selection, and memory cells', 'Muscle contraction and sliding filament theory'],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
    ],
  },

  {
    id: 'ib-economics',
    curriculum: 'IB',
    subject: 'Economics',
    icon: 'TrendingUp',
    topics: [
      {
        id: 'ib-econ-u1',
        name: 'Unit 1: Introduction to Economics (Core SL/HL)',
        subtopics: ['Scarcity, choice, and opportunity cost', 'Production possibilities curves (PPC)', 'Circular flow of income model'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-econ-u2-core',
        name: 'Unit 2: Microeconomics (Core SL/HL)',
        subtopics: ['Demand, supply, competitive market equilibrium', 'Price elasticity of demand (PED) and supply (PES)', 'Government intervention: indirect taxes, subsidies, price ceilings/floors', 'Market failure: positive and negative externalities, public goods'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-econ-u2-hl',
        name: 'Unit 2: Economics of the Firm (HL Extension)',
        subtopics: ['Short-run and long-run costs, revenues, and profit maximization (MR = MC)', 'Perfect competition vs pure monopoly', 'Monopolistic competition and oligopoly game theory (prisoner dilemma)', 'Price discrimination and government regulation of monopolies'],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-econ-u3-core',
        name: 'Unit 3: Macroeconomics (Core SL/HL)',
        subtopics: ['Measuring economic activity: GDP and GNI', 'Aggregate demand (AD) and aggregate supply (AS)', 'Macroeconomic objectives: inflation, unemployment, economic growth', 'Monetary policy and fiscal policy interventions'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-econ-u3-hl',
        name: 'Unit 3: Macroeconomic Multipliers & Phillips Curve (HL Extension)',
        subtopics: ['Keynesian multiplier calculation: k = 1 / (1 - MPC)', 'Short-run vs long-run Phillips curve and stagflation', 'Monetary transmission mechanism and supply-side growth policies'],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-econ-u4',
        name: 'Unit 4: The Global Economy (Core SL/HL)',
        subtopics: ['Benefits of international trade & comparative advantage', 'Trade protectionism: tariffs, quotas, subsidies', 'Floating vs fixed exchange rates and currency appreciation/depreciation', 'Balance of payments and economic development indicators'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
    ],
  },

  {
    id: 'ib-business-management',
    curriculum: 'IB',
    subject: 'Business Management',
    icon: 'Briefcase',
    topics: [
      {
        id: 'ib-bm-u1',
        name: 'Unit 1: Introduction to Business Management',
        subtopics: ['Types of business entities: sole traders, partnerships, corporations', 'Business objectives, mission, vision, and CSR', 'Stakeholder analysis and conflict resolution', 'Growth and evolution: internal growth, mergers, and franchising'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-bm-u2-core',
        name: 'Unit 2: Human Resource Management (Core SL/HL)',
        subtopics: ['HR planning, recruitment, and appraisal', 'Organizational structure: delegation, span of control, hierarchy', 'Leadership styles and motivation theories (Taylor, Maslow, Herzberg)'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-bm-u2-hl',
        name: 'Unit 2: Organizational Culture & Industrial Relations (HL Extension)',
        subtopics: ["Handy's cultural types: power, role, task, person culture", 'Trade unions and collective bargaining', 'Industrial dispute resolution: conciliation, arbitration, strike actions'],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-bm-u3-core',
        name: 'Unit 3: Finance and Accounts (Core SL/HL)',
        subtopics: ['Internal and external sources of finance', 'Costs, revenues, and break-even analysis (BEQ)', 'Profit and loss statement and balance sheet accounts', 'Cash flow forecasting and liquidity management'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-bm-u3-hl',
        name: 'Unit 3: Investment Appraisal & Budgets (HL Extension)',
        subtopics: ['Payback period and Average Rate of Return (ARR)', 'Net Present Value (NPV) using discounted cash flows', 'Budgeting: variance analysis and cost centers'],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-bm-u4-core',
        name: 'Unit 4: Marketing (Core SL/HL)',
        subtopics: ['Market research: primary and secondary methodologies', 'The 4 Ps: Product life cycle, Boston Matrix, pricing strategies', 'Promotion: above-the-line and below-the-line methods', 'Place and distribution channels'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-bm-u4-hl',
        name: 'Unit 4: The 7 Ps & International Marketing (HL Extension)',
        subtopics: ['The extended marketing mix: People, Processes, Physical evidence (7 Ps)', 'Sales forecasting using three-point moving averages', 'International marketing: entry strategies, cultural adaptation, globalization'],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-bm-u5-core',
        name: 'Unit 5: Operations Management (Core SL/HL)',
        subtopics: ['Methods of production: job, batch, mass, cellular', 'Location decisions and international relocation factors'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-bm-u5-hl',
        name: 'Unit 5: Lean Production & Crisis Planning (HL Extension)',
        subtopics: ['Lean production: Just-in-Time (JIT), Kaizen, and waste minimization', 'Total Quality Management (TQM) and quality control vs assurance', 'Crisis management and contingency planning'],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
    ],
  },

  {
    id: 'ib-global-politics',
    curriculum: 'IB',
    subject: 'Global Politics',
    icon: 'Globe',
    topics: [
      {
        id: 'ib-gp-u1',
        name: 'Unit 1: Power, Sovereignty & International Relations',
        subtopics: ['The nature of power: hard power, soft power, smart power', 'State sovereignty and challenges to the nation-state', 'Legitimacy, authority, and global governance (UN, IMF, WTO)'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-gp-u2',
        name: 'Unit 2: Human Rights',
        subtopics: ['Nature and evolution of human rights (Universal Declaration)', 'Universalism vs cultural relativism debate', 'Human rights enforcement: treaties, tribunals, and human rights courts'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-gp-u3',
        name: 'Unit 3: Development',
        subtopics: ['Contested definitions of development: GDP vs Human Development Index (HDI)', 'Factors promoting and inhibiting sustainable development', 'Inequality, poverty traps, and globalization effects'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-gp-u4',
        name: 'Unit 4: Peace and Conflict',
        subtopics: ['Conceptions of peace: negative peace vs positive peace', 'Structural and direct violence; causes and escalations of war', 'Conflict resolution: peacekeeping, peacebuilding, and mediation'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-gp-hl-extension',
        name: 'HL Extension: Global Political Challenges (HL Extension)',
        subtopics: ['Environment and sustainability challenges: climate diplomacy and resource conflicts', 'Poverty, global health crises, and cross-border pandemics', 'International migration, borders, and statelessness', 'Conducting and presenting two in-depth contemporary case studies'],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
    ],
  },

  {
    id: 'ib-english-lit',
    curriculum: 'IB',
    subject: 'English A: Literature',
    icon: 'BookOpen',
    topics: [
      {
        id: 'ib-eng-p1',
        name: 'Paper 1: Guided Literary Analysis',
        subtopics: ['Close reading techniques for unseen poetry, prose fiction, drama, literary non-fiction', 'Analyzing authorial choices: tone, imagery, syntax, diction, structure', 'Formulating a sustained, thesis-driven critical commentary'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-eng-p2',
        name: 'Paper 2: Comparative Literary Essay',
        subtopics: ['Comparative essay structure comparing two studied literary works', 'Synthesizing themes, literary conventions, and contextual resonance', 'Responding effectively to unseen general examination prompts'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-eng-hle-hl',
        name: 'Higher Level (HL) Essay (HL Extension)',
        subtopics: ['1,200 to 1,500 word formal analytical investigation', 'Developing an independent research inquiry into one studied literary work', 'Academic citation, critical theory, and formal literary register'],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-eng-io',
        name: 'Individual Oral (IO)',
        subtopics: ['Exploring a Global Issue across a literary work and work in translation', '10-minute student presentation followed by 5-minute teacher discussion', 'Balanced textual close-reading of extracts and the works as a whole'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
    ],
  },

  {
    id: 'ib-history',
    curriculum: 'IB',
    subject: 'History',
    icon: 'Landmark',
    topics: [
      {
        id: 'ib-hist-p1',
        name: 'Paper 1: Prescribed Source Analysis',
        subtopics: ['Conflict and intervention / Rights and protest (Civil Rights, Apartheid)', 'Evaluating historical sources: Origin, Purpose, Content, Values, Limitations (OPCVL)'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-hist-p2',
        name: 'Paper 2: World History Topics',
        subtopics: ['Authoritarian States (20th Century): Rise, consolidation, domestic policies', 'Causes and effects of 20th century wars', 'The Cold War: Superpower tensions, proxy wars, detente, and collapse'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-hist-p3-hl',
        name: 'Paper 3: Regional In-Depth Studies (HL Extension)',
        subtopics: ['History of Asia and Oceania (or Americas/Europe depth study)', 'Nationalism, independence, and political developments in East and Southeast Asia', 'Comprehensive multi-source comparative historical essays'],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
    ],
  },

  {
    id: 'ib-psychology',
    curriculum: 'IB',
    subject: 'Psychology',
    icon: 'Brain',
    topics: [
      {
        id: 'ib-psych-core',
        name: 'Core Approaches to Understanding Behaviour (Core SL/HL)',
        subtopics: ['Biological approach: brain localization, neuroplasticity, neurotransmitters, hormones, genetics', 'Cognitive approach: models of memory (MSM, WMM), schema theory, cognitive biases', 'Sociocultural approach: social identity theory, stereotypes, enculturation, cultural dimensions'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-psych-hl-ext',
        name: 'HL Extension: Technology & Animal Research (HL Extension)',
        subtopics: ['The value and ethics of animal models in psychological research', 'Cognitive processing in digital environments: reliability, memory, emotion', 'Qualitative research methods: interviews, observations, and case studies'],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-psych-options',
        name: 'Applied Psychology Options',
        subtopics: ['Abnormal psychology: diagnosis, etiology, and treatments for depression', 'Human relationships: formation of personal relationships, prosocial behavior, and prejudice'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
    ],
  },

  {
    id: 'ib-computer-science',
    curriculum: 'IB',
    subject: 'Computer Science',
    icon: 'Laptop',
    topics: [
      {
        id: 'ib-cs-t1-4-core',
        name: 'Topics 1-4: Systems, Architecture & Java (Core SL/HL)',
        subtopics: ['System design fundamentals, stakeholders, data security', 'Computer organization: CPU, cache, memory, registers, operating systems', 'Networks: topologies, data transmission, wireless security', 'Computational thinking: pseudocode algorithms, search and sorting algorithms'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-cs-t5-7-hl',
        name: 'Topics 5-7: Abstract Data Structures & Systems (HL Extension)',
        subtopics: ['Abstract data structures: 2D arrays, stacks, queues, linked lists, binary trees', 'Resource management: operating system resource allocation and interrupts', 'Control systems: sensors, microprocessors, feedback loops, real-time control'],
        isHlOnly: true,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
    ],
  },

  {
    id: 'ib-tok',
    curriculum: 'IB',
    subject: 'Theory of Knowledge (TOK)',
    icon: 'Sparkles',
    topics: [
      {
        id: 'ib-tok-core',
        name: 'Core Theme: Knowledge and the Knower',
        subtopics: ['How personal experience, culture, and perspective shape knowledge', 'Biases, cognitive illusions, and ethical responsibilities of the knower', 'Justification, truth, belief, and certainty'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-tok-aok',
        name: 'Areas of Knowledge (AOKs)',
        subtopics: ['Natural Sciences: scientific method, falsification, paradigm shifts', 'Human Sciences: measuring human behavior, ethics in experiments', 'History: historical evidence, selection bias, historiography', 'The Arts: subjective interpretation, emotion, aesthetics', 'Mathematics: deductive reasoning, axioms, mathematical certainty'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-tok-assessments',
        name: 'TOK Assessments: Exhibition & Prescribed Essay',
        subtopics: ['TOK Exhibition: selecting 3 real-world objects for a 950-word commentary', 'TOK Essay: tackling one of 6 prescribed titles (1,600 words)', 'Formulating strong knowledge questions and real-world counterclaims'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
    ],
  },

  {
    id: 'ib-ee-lab',
    curriculum: 'IB',
    subject: 'Extended Essay (EE) Lab',
    icon: 'GraduationCap',
    topics: [
      {
        id: 'ib-ee-stage1',
        name: 'Stage 1: Research Question & Proposal',
        subtopics: ['Selecting an appropriate academic discipline', 'Formulating a clear, focused, and arguable Research Question (RQ)', 'Ethical guidelines and preliminary literature exploration'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-ee-stage2',
        name: 'Stage 2: Research Methodology & Evidence Gathering',
        subtopics: ['Primary data collection vs secondary academic literature', 'Evaluating source credibility, peer-reviewed journals, and data validity', 'Organizing chapter outlines and bibliography tracking'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ib-ee-stage3',
        name: 'Stage 3: Writing, Analysis & Reflection (RPPF)',
        subtopics: ['Developing a sustained, logical line of reasoned argument', 'Criterion E: Reflections on Planning and Progress Form (RPPF)', 'Formatting, citations (APA/MLA/Chicago), and the Viva Voce concluding interview'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
    ],
  },

  // ==========================================================================
  // 2. ADVANCED PLACEMENT (AP)
  // ==========================================================================
  {
    id: 'ap-calculus-bc',
    curriculum: 'AP',
    subject: 'AP Calculus BC',
    icon: 'Calculator',
    hasCalculator: true,
    defaultCalculatorMode: 'graphing',
    topics: [
      {
        id: 'ap-calc-bc-u1-2',
        name: 'Units 1-2: Limits, Continuity & Derivative Rules',
        subtopics: ['Limits and continuity (IVT)', 'Definition of derivative', 'Power, product, quotient, and chain rules'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ap-calc-bc-u3-5',
        name: 'Units 3-5: Implicit, Related Rates & Extrema',
        subtopics: ['Implicit differentiation & inverse functions', 'Related rates', "MVT, concavity, optimization, and L'Hopital rule"],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ap-calc-bc-u6-8',
        name: 'Units 6-8: Integration & Volumes of Revolution',
        subtopics: ['Riemann sums and Fundamental Theorem of Calculus', 'Integration by parts & partial fractions', 'Improper integrals, disk/washer method, arc length'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ap-calc-bc-u7-9',
        name: 'Units 7 & 9: Differential Equations, Parametric & Polar',
        subtopics: ['Slope fields and Euler method', 'Separable differential equations', 'Parametric equations and polar curve area integrals'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ap-calc-bc-u10',
        name: 'Unit 10: Infinite Sequences and Series',
        subtopics: ['Convergence tests (ratio, root, integral, alternating)', 'Taylor and Maclaurin polynomials', 'Lagrange error bound and interval of convergence'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
    ],
  },

  {
    id: 'ap-calculus-ab',
    curriculum: 'AP',
    subject: 'AP Calculus AB',
    icon: 'Calculator',
    hasCalculator: true,
    defaultCalculatorMode: 'graphing',
    topics: [
      {
        id: 'ap-calc-ab-u1-2',
        name: 'Units 1-2: Limits & Continuity',
        subtopics: ['Limit evaluating techniques', 'Asymptotes and continuity', 'Definition of the derivative'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ap-calc-ab-u3-5',
        name: 'Units 3-5: Differentiation Applications',
        subtopics: ['Product, quotient, chain rule', 'Related rates', 'Function analysis (first/second derivative test) and optimization'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ap-calc-ab-u6-8',
        name: 'Units 6-8: Integration & Differential Equations',
        subtopics: ['Antiderivatives and u-substitution', 'Fundamental Theorem of Calculus', 'Area between curves and volumes of revolution'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
    ],
  },

  {
    id: 'ap-physics-c-mechanics',
    curriculum: 'AP',
    subject: 'AP Physics C: Mechanics',
    icon: 'Zap',
    hasCalculator: true,
    defaultCalculatorMode: 'scientific',
    topics: [
      {
        id: 'ap-phys-c-u1-2',
        name: 'Units 1-2: Kinematics & Newton Laws with Calculus',
        subtopics: ['Calculus-based kinematics (derivatives/integrals)', 'Drag forces and differential equations', 'Frictional dynamics on inclines'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ap-phys-c-u3-4',
        name: 'Units 3-4: Work, Energy, Momentum & Center of Mass',
        subtopics: ['Work as variable integral: W = integral F dx', 'Potential energy functions: F = -dU/dx', 'Impulse, momentum, and continuous center of mass'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ap-phys-c-u5',
        name: 'Unit 5: Rotational Dynamics & Angular Momentum',
        subtopics: ['Moments of inertia by integration and parallel axis theorem', 'Torque: sum(tau) = I*alpha', 'Rolling without slipping and conservation of L'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ap-phys-c-u6-7',
        name: 'Units 6-7: Simple Harmonic Motion & Gravitation',
        subtopics: ['SHM differential equation and physical pendulums', 'Universal gravitation, potential energy, and orbital mechanics'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
    ],
  },

  {
    id: 'ap-physics-1',
    curriculum: 'AP',
    subject: 'AP Physics 1',
    icon: 'Atom',
    hasCalculator: true,
    defaultCalculatorMode: 'scientific',
    topics: [
      {
        id: 'ap-phys-1-u1-2',
        name: 'Units 1-2: Kinematics & Dynamics',
        subtopics: ['1D/2D Kinematics and projectile motion', 'Newton laws, free body diagrams, and friction'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ap-phys-1-u3-4',
        name: 'Units 3-4: Circular Motion, Work, and Energy',
        subtopics: ['Centripetal acceleration and gravity', 'Work-energy theorem and conservation of mechanical energy'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ap-phys-1-u5-7',
        name: 'Units 5-7: Momentum, SHM & Rotational Motion',
        subtopics: ['Linear momentum conservation in collisions', 'Simple harmonic motion: springs and pendulums', 'Rotational kinematics, torque, and angular momentum'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
    ],
  },

  {
    id: 'ap-chemistry',
    curriculum: 'AP',
    subject: 'AP Chemistry',
    icon: 'FlaskConical',
    hasCalculator: true,
    defaultCalculatorMode: 'scientific',
    topics: [
      {
        id: 'ap-chem-u1-3',
        name: 'Units 1-3: Atomic Structure, Bonding & Intermolecular',
        subtopics: ['Moles, mass spec, periodic trends', 'Chemical bonding models and Lewis structures', 'Intermolecular forces, phase diagrams, solutions'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ap-chem-u4-6',
        name: 'Units 4-6: Chemical Reactions, Kinetics & Thermochemistry',
        subtopics: ['Net ionic equations, redox, stoichiometry', 'Rate laws, half-life, reaction mechanisms', 'Enthalpy of reaction, calorimetry, Hess law'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ap-chem-u7-9',
        name: 'Units 7-9: Equilibrium, Acids/Bases & Thermodynamics',
        subtopics: ['Equilibrium constant K and Le Chatelier', 'pH, buffer solutions, titration curves', 'Entropy, Gibbs free energy, and electrochemistry'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
    ],
  },

  {
    id: 'ap-biology',
    curriculum: 'AP',
    subject: 'AP Biology',
    icon: 'Dna',
    hasCalculator: true,
    defaultCalculatorMode: 'scientific',
    topics: [
      {
        id: 'ap-bio-u1-2',
        name: 'Units 1-2: Chemistry of Life & Cell Structure',
        subtopics: ['Water properties, macromolecules (proteins, carbs, lipids, nucleic acids)', 'Cell organelles, membrane permeability, and tonicity'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ap-bio-u3-4',
        name: 'Units 3-4: Cellular Energetics & Communication',
        subtopics: ['Enzymatic catalysis', 'Cellular respiration and photosynthesis', 'Signal transduction pathways, feedback loops, cell cycle'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ap-bio-u5-6',
        name: 'Units 5-6: Heredity & Gene Expression',
        subtopics: ['Meiosis and genetic diversity', 'Mendelian and non-Mendelian genetics', 'DNA replication, transcription, translation, and biotechnology'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ap-bio-u7-8',
        name: 'Units 7-8: Natural Selection & Ecology',
        subtopics: ['Hardy-Weinberg equilibrium and speciation', 'Phylogenetic trees and cladograms', 'Community ecology, trophic energy, biodiversity'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
    ],
  },

  {
    id: 'ap-english-lang',
    curriculum: 'AP',
    subject: 'AP English Language',
    icon: 'BookOpen',
    topics: [
      {
        id: 'ap-eng-lang-q1',
        name: 'Synthesis Essay (FRQ 1)',
        subtopics: ['Reading and synthesizing 6-7 diverse sources', 'Developing an evidence-backed argumentative thesis', 'Attributing and contextualizing source perspectives'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ap-eng-lang-q2',
        name: 'Rhetorical Analysis Essay (FRQ 2)',
        subtopics: ['Identifying the rhetorical situation: author, audience, purpose, context, exigence', 'Analyzing rhetorical choices: diction, syntax, appeals (ethos, pathos, logos)', 'Explaining how choices achieve the author purpose'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ap-eng-lang-q3',
        name: 'Argument Essay (FRQ 3)',
        subtopics: ['Taking a defensible stance on a philosophical, societal, or moral prompt', 'Using broad evidence from history, literature, and current events', 'Sophistication points: addressing nuances and counterarguments'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
    ],
  },

  {
    id: 'ap-microeconomics',
    curriculum: 'AP',
    subject: 'AP Microeconomics',
    icon: 'TrendingUp',
    topics: [
      {
        id: 'ap-micro-u1-2',
        name: 'Units 1-2: Supply, Demand & Elasticity',
        subtopics: ['Scarcity, choice, and opportunity cost', 'Demand, supply, consumer/producer surplus', 'Price elasticity of demand/supply, taxes, tariffs'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ap-micro-u3-4',
        name: 'Units 3-4: Production Costs & Market Structures',
        subtopics: ['Short-run costs (MC, ATC, AVC) and economies of scale', 'Perfect competition profit-maximization (MR = MC)', 'Monopoly, price discrimination, and oligopoly game theory'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ap-micro-u5-6',
        name: 'Units 5-6: Factor Markets & Market Failure',
        subtopics: ['Marginal revenue product (MRP) and labor markets', 'Externalities (positive and negative)', 'Public goods, common resources, and income inequality'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
    ],
  },

  {
    id: 'ap-macroeconomics',
    curriculum: 'AP',
    subject: 'AP Macroeconomics',
    icon: 'TrendingUp',
    topics: [
      {
        id: 'ap-macro-u1-2',
        name: 'Units 1-2: Economic Indicators & Business Cycle',
        subtopics: ['Circular flow, GDP calculations, real vs nominal GDP', 'Unemployment rate and types of unemployment', 'Consumer Price Index (CPI) and inflation calculations'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ap-macro-u3-4',
        name: 'Units 3-4: AD/AS Framework & Financial Sector',
        subtopics: ['Aggregate demand, short-run and long-run aggregate supply', 'Fiscal policy and spending/tax multipliers', 'Money market, bank balance sheets, and monetary policy (reserve requirements, discount rate, open market)'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ap-macro-u5-6',
        name: 'Units 5-6: Stabilization Policies & International Trade',
        subtopics: ['Phillips curve and economic growth policies', 'Current account vs financial account balance', 'Foreign exchange market (FOREX) and currency appreciation/depreciation'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
    ],
  },

  {
    id: 'ap-csa',
    curriculum: 'AP',
    subject: 'AP Computer Science A',
    icon: 'Laptop',
    topics: [
      {
        id: 'ap-csa-u1-4',
        name: 'Units 1-4: Java Fundamentals, Logic & Iteration',
        subtopics: ['Primitive data types, operators, and casting', 'Using objects, String class methods', 'Boolean expressions, if statements, and de Morgan laws', 'While loops, for loops, and nested iterations'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ap-csa-u5-7',
        name: 'Units 5-7: Class Design, Arrays & ArrayList',
        subtopics: ['Writing classes: constructors, encapsulation, methods, static keyword', '1D arrays: traversal, algorithms, algorithms (min, max, reverse)', 'ArrayList: methods, wrapper classes, auto-boxing'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ap-csa-u8-10',
        name: 'Units 8-10: 2D Arrays, Inheritance & Recursion',
        subtopics: ['2D arrays: row-major vs column-major traversal', 'Inheritance: super keyword, method overriding, polymorphism', 'Recursion: recursive methods, base cases, binary search, merge sort'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
    ],
  },

  {
    id: 'ap-world-history',
    curriculum: 'AP',
    subject: 'AP World History',
    icon: 'Landmark',
    topics: [
      {
        id: 'ap-world-u1-2',
        name: 'Units 1-2: Global Tapestry & Networks of Exchange (1200-1450)',
        subtopics: ['State building in Song China, Dar al-Islam, and the Americas', 'Silk Roads, Indian Ocean trade, and Trans-Saharan trade', 'The Mongol Empire and its Eurasian impact'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ap-world-u3-6',
        name: 'Units 3-6: Land Empires, Transoceanic & Revolutions (1450-1900)',
        subtopics: ['Gunpowder empires (Ottoman, Safavid, Mughal, Qing)', 'Columbian exchange, maritime empires, and plantation economy', 'Enlightenment revolutions (American, French, Haitian, Latin American)', 'Industrial Revolution and imperial expansion in Africa and Asia'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'ap-world-u7-9',
        name: 'Units 7-9: Global Conflicts & Globalization (1900-Present)',
        subtopics: ['World War I and World War II causes and global consequences', 'The Cold War and decolonization in Africa, Asia, and Middle East', 'Technological globalization, international organizations, and modern resistance'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
    ],
  },

  // ==========================================================================
  // 3. CAMBRIDGE / EDEXCEL IGCSE
  // ==========================================================================
  {
    id: 'igcse-extended-math',
    curriculum: 'IGCSE',
    subject: 'IGCSE Extended Mathematics',
    icon: 'Compass',
    hasCalculator: true,
    defaultCalculatorMode: 'scientific',
    topics: [
      {
        id: 'igcse-ext-t1',
        name: 'Topic 1: Number & Arithmetic',
        subtopics: ['Prime numbers, factors, HCF and LCM', 'Fractions, decimals, percentages, standard form', 'Upper and lower bounds of rounded values', 'Ratio, direct/inverse proportion, compound interest'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'igcse-ext-t2',
        name: 'Topic 2: Algebra & Graphs',
        subtopics: ['Algebraic manipulation and factorisation', 'Quadratic formula and simultaneous equations', 'Linear inequalities and shaded graph regions', 'Functions, composite functions, and inverse functions'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'igcse-ext-t3',
        name: 'Topic 3: Coordinate Geometry & Functions',
        subtopics: ['Gradient, midpoint, distance between two points', 'Equation of straight lines: y = mx + c', 'Parallel and perpendicular gradients'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'igcse-ext-t4',
        name: 'Topic 4: Geometry, Circle Theorems & Mensuration',
        subtopics: ['Angle properties of polygons and parallel lines', 'Circle theorems (angles subtended by arcs, cyclic quads)', 'Perimeter, area, volume of composite 3D shapes'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'igcse-ext-t5',
        name: 'Topic 5: Trigonometry',
        subtopics: ['SOH CAH TOA in right-angled triangles', 'Angles of elevation, depression, bearings', 'Sine rule, cosine rule, area of triangle = 1/2 ab sin(C)', '3D trigonometry problems'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'igcse-ext-t6',
        name: 'Topic 6: Vectors & Transformations',
        subtopics: ['Column vectors and scalar multiplication', 'Vector geometric proofs', 'Transformations: translation, reflection, rotation, enlargement'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'igcse-ext-t7',
        name: 'Topic 7: Probability & Statistics',
        subtopics: ['Probability trees and Venn diagrams', 'Averages: mean, median, mode, range', 'Cumulative frequency curves, median, IQR, histograms'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
    ],
  },

  {
    id: 'igcse-add-math',
    curriculum: 'IGCSE',
    subject: 'IGCSE Additional Mathematics',
    icon: 'Calculator',
    hasCalculator: true,
    defaultCalculatorMode: 'scientific',
    topics: [
      {
        id: 'igcse-add-t1-3',
        name: 'Topics 1-3: Functions, Quadratics & Polynomials',
        subtopics: ['Domain, range, inverse, and composite functions', 'Quadratic inequalities and discriminant analysis', 'Remainder and factor theorems, cubic factorisation'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'igcse-add-t4-6',
        name: 'Topics 4-6: Exponentials, Logs & Binomial Theorem',
        subtopics: ['Laws of indices and logarithms', 'Exponential growth equations', 'Binomial expansion: (a + b)^n for positive integers'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'igcse-add-t7-9',
        name: 'Topics 7-9: Trig Identities, Vectors & Permutations',
        subtopics: ['Radian measure and circular geometry', 'Trig identities: tan(theta), sin^2 + cos^2 = 1, sec, cosec, cot', '2D vectors and scalar products', 'Permutations and combinations'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'igcse-add-t10-12',
        name: 'Topics 10-12: Introductory Calculus',
        subtopics: ['Differentiation (product, quotient, chain rule)', 'Stationary points, max/min, connected rates of change', 'Integration of polynomial, trig, and exponential terms', 'Area under a curve and kinematic applications'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
    ],
  },

  {
    id: 'igcse-physics',
    curriculum: 'IGCSE',
    subject: 'IGCSE Physics (0625)',
    icon: 'Atom',
    hasCalculator: true,
    defaultCalculatorMode: 'scientific',
    topics: [
      {
        id: 'igcse-phys-t1',
        name: 'Section 1: Motion, Forces & Energy',
        subtopics: ['Speed, velocity, acceleration graphs', 'Mass, weight, density, and Newton laws', 'Work, energy resources, efficiency, and power'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'igcse-phys-t2-3',
        name: 'Sections 2-3: Thermal Physics & Waves',
        subtopics: ['States of matter and kinetic particle model', 'Conduction, convection, radiation', 'Light reflection/refraction, electromagnetic spectrum, sound waves'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'igcse-phys-t4-5',
        name: 'Sections 4-5: Electricity, Magnetism & Nuclear',
        subtopics: ['Simple circuits, current, voltage, resistance, power', 'Electromagnetism and motor effect', 'Radioactive decay (alpha, beta, gamma), half-life'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
    ],
  },

  {
    id: 'igcse-chemistry',
    curriculum: 'IGCSE',
    subject: 'IGCSE Chemistry (0620)',
    icon: 'FlaskConical',
    hasCalculator: true,
    defaultCalculatorMode: 'scientific',
    topics: [
      {
        id: 'igcse-chem-t1-3',
        name: 'Topics 1-3: States, Atomic Structure & Bonding',
        subtopics: ['Particulate nature of matter and diffusion', 'Atomic structure, isotopes, electron configuration', 'Ionic, covalent, and metallic lattice bonding'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'igcse-chem-t4-6',
        name: 'Topics 4-6: Stoichiometry, Energetics & Kinetics',
        subtopics: ['Moles, concentration, reacting mass calculations', 'Exothermic and endothermic reactions', 'Rates of reaction and catalysts'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'igcse-chem-t7-10',
        name: 'Topics 7-10: Acids, Bases, Metals & Organic Chemistry',
        subtopics: ['Oxides, acid-base reactions, salt preparation', 'Periodic trends and transition metals', 'Alkanes, alkenes, alcohols, carboxylic acids, polymers'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
    ],
  },

  {
    id: 'igcse-biology',
    curriculum: 'IGCSE',
    subject: 'IGCSE Biology (0610)',
    icon: 'Dna',
    hasCalculator: true,
    defaultCalculatorMode: 'scientific',
    topics: [
      {
        id: 'igcse-bio-t1-4',
        name: 'Topics 1-4: Cell Biology, Movement & Biological Molecules',
        subtopics: ['Classification of living organisms', 'Cell structure and organization', 'Diffusion, osmosis, and active transport', 'Enzymes and biological nutrition'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'igcse-bio-t5-8',
        name: 'Topics 5-8: Plant & Animal Physiology',
        subtopics: ['Plant nutrition, photosynthesis, xylem/phloem transport', 'Human digestion, circulatory system, gas exchange', 'Respiration, excretion, and nervous coordination'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'igcse-bio-t9-12',
        name: 'Topics 9-12: Reproduction, Inheritance & Ecology',
        subtopics: ['Asexual vs sexual reproduction in plants and humans', 'Inheritance, monohybrid crosses, and DNA', 'Food chains, carbon cycle, and human impact on ecosystems'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
    ],
  },

  {
    id: 'igcse-economics',
    curriculum: 'IGCSE',
    subject: 'IGCSE Economics',
    icon: 'TrendingUp',
    topics: [
      {
        id: 'igcse-econ-t1-2',
        name: 'Units 1-2: Basic Problem & Allocation of Resources',
        subtopics: ['Factors of production, opportunity cost, PPC', 'Demand, supply, equilibrium, and price elasticity'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'igcse-econ-t3-4',
        name: 'Units 3-4: Microeconomics & Government Decisions',
        subtopics: ['Money, banking, households, workers, trade unions', 'Firms: costs, revenues, competition, and monopoly', 'Government macroeconomic aims: inflation, growth, employment'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'igcse-econ-t5-6',
        name: 'Units 5-6: Economic Development & Global Economy',
        subtopics: ['Living standards, poverty, population growth', 'International specialization, trade protection, exchange rates'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
    ],
  },

  {
    id: 'igcse-english-lang',
    curriculum: 'IGCSE',
    subject: 'IGCSE English First Language',
    icon: 'BookOpen',
    topics: [
      {
        id: 'igcse-eng-p1',
        name: 'Paper 1: Reading Comprehension & Summary',
        subtopics: ['Comprehension questions on unseen non-fiction texts', 'Summary task: extracting 10-15 key points concisely in own words', 'Extended response to reading: writing as a character or journalist'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
      {
        id: 'igcse-eng-p2',
        name: 'Paper 2: Directed Writing & Composition',
        subtopics: ['Directed writing: responding to two texts (speech, letter, article)', 'Descriptive writing: sensory detail, atmospheric scene building', 'Narrative writing: plot pacing, character arcs, effective endings'],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [],
      },
    ],
  },

  // ==========================================================================
  // 4. STANDARDIZED TESTS (DIGITAL SAT)
  // ==========================================================================
  {
    id: 'digital-sat-math',
    curriculum: 'SAT_ACT',
    subject: 'Digital SAT Math (Advanced & Desmos)',
    icon: 'Target',
    topics: [
      {
        id: 'sat-official-qb-practice',
        name: 'Official Question Bank & Full Practice Tests',
        subtopics: [
          'College Board Official SAT Suite Question Bank (Thousands of real test items)',
          'Bluebook app 6 adaptive full-length official tests',
          'Official College Board printable linear test papers',
          'Digital SAT score conversion and skill-gap diagnostic',
        ],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [
          {
            id: 'pp-sat-linear-1',
            title: 'Official Digital SAT Linear Non-Adaptive Practice Test 1',
            url: 'https://satsuite.collegeboard.org/media/pdf/sat-practice-test-1-digital.pdf',
            year: 2024,
            session: 'may',
            paper: 1,
            hasMarkscheme: true,
            markschemeUrl: 'https://satsuite.collegeboard.org/media/pdf/sat-practice-test-1-answers-digital.pdf',
          },
          {
            id: 'pp-sat-linear-2',
            title: 'Official Digital SAT Linear Non-Adaptive Practice Test 2',
            url: 'https://satsuite.collegeboard.org/media/pdf/sat-practice-test-2-digital.pdf',
            year: 2024,
            session: 'may',
            paper: 2,
            hasMarkscheme: true,
            markschemeUrl: 'https://satsuite.collegeboard.org/media/pdf/sat-practice-test-2-answers-digital.pdf',
          },
        ],
        externalResources: [
          {
            id: 'ext-sat-qb-main',
            title: 'College Board Official SAT Suite Question Bank',
            url: 'https://satsuitequestionbank.collegeboard.org/',
            source: 'College Board',
            description: 'Official repository containing thousands of real active SAT Math questions filterable by Domain, Skill, and Difficulty level.',
          },
          {
            id: 'ext-sat-bluebook',
            title: 'College Board Bluebook Testing Application',
            url: 'https://bluebook.collegeboard.org/',
            source: 'College Board',
            description: 'Official testing client containing 6 full-length adaptive Digital SAT exams with instant scoring and explanation analytics.',
          },
        ],
      },
      {
        id: 'sat-math-algebra',
        name: 'Heart of Algebra & Desmos Strategies',
        subtopics: [
          'Linear equations in one and two variables',
          'Linear functions, slope, and intercepts',
          'Systems of linear equations (algebraic and graphical solving)',
          'Linear inequalities and systems of inequalities',
          'Desmos graphing calculator tips: slider tricks and regression equations',
        ],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [
          {
            id: 'ext-sat-alg-1',
            title: 'Khan Academy - Official Digital SAT Algebra Core Skills',
            url: 'https://www.khanacademy.org/test-prep/v2-sat-prep/x0fcc98a58ba3be7a:algebra-core-skills',
            source: 'Khan Academy',
            description: 'Official College Board partner lessons, timed mini-sections, and step-by-step walkthroughs.',
          },
        ],
      },
      {
        id: 'sat-math-advanced',
        name: 'Advanced Math: Quadratics, Exponentials & Polynomials',
        subtopics: [
          'Equivalent expressions and polynomial factoring',
          'Nonlinear equations: quadratic formula, completing the square, discriminant',
          'Exponential functions, percent growth/decay, and compound interest',
          'Radical and rational equations and extraneous solutions',
          'Desmos techniques: finding vertex, roots, and intersections instantly',
        ],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [
          {
            id: 'ext-sat-adv-1',
            title: 'Khan Academy - Official Digital SAT Advanced Math Core Skills',
            url: 'https://www.khanacademy.org/test-prep/v2-sat-prep/x0fcc98a58ba3be7a:advanced-math-core-skills',
            source: 'Khan Academy',
            description: 'In-depth practice covering quadratics, exponential growth models, and higher-order polynomials.',
          },
        ],
      },
      {
        id: 'sat-math-problem-solving',
        name: 'Problem-Solving and Data Analysis',
        subtopics: [
          'Ratios, rates, proportional relationships, and unit conversion',
          'Percentages, percent change, and multi-step word problems',
          'One-variable data: mean, median, mode, range, and standard deviation',
          'Two-variable data: scatterplots, lines of best fit, and correlation',
          'Probability and conditional probability from two-way frequency tables',
        ],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [
          {
            id: 'ext-sat-data-1',
            title: 'Khan Academy - Official Digital SAT Problem-Solving & Data Analysis',
            url: 'https://www.khanacademy.org/test-prep/v2-sat-prep/x0fcc98a58ba3be7a:problem-solving-and-data-analysis-core-skills',
            source: 'Khan Academy',
            description: 'Targeted exercises for data distributions, percentages, scatterplots, and statistical inferences.',
          },
        ],
      },
      {
        id: 'sat-math-geom-trig',
        name: 'Geometry and Trigonometry',
        subtopics: [
          'Area, perimeter, and surface area of 2D and 3D figures',
          'Angles, triangles, congruence, and similarity',
          'Right triangle trigonometry: sine, cosine, tangent ratios and unit circle',
          'Circle equations, arc length, and sector area',
        ],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [
          {
            id: 'ext-sat-geom-1',
            title: 'Khan Academy - Official Digital SAT Geometry & Trigonometry',
            url: 'https://www.khanacademy.org/test-prep/v2-sat-prep/x0fcc98a58ba3be7a:geometry-and-trigonometry-core-skills',
            source: 'Khan Academy',
            description: 'Official prep covering right triangle trig, circle theorems, and coordinate geometry.',
          },
        ],
      },
    ],
  },

  {
    id: 'digital-sat-reading-writing',
    curriculum: 'SAT_ACT',
    subject: 'Digital SAT Reading & Writing',
    icon: 'BookOpen',
    topics: [
      {
        id: 'sat-rw-official-qb',
        name: 'Official Question Bank & Bluebook Prep',
        subtopics: [
          'Official SAT Suite Question Bank for Reading & Writing',
          'Bluebook official tests 1-6 reading section analysis',
          'Pacing strategy for 27 questions in 32 minutes per module',
        ],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [
          {
            id: 'ext-sat-rw-qb',
            title: 'College Board Official SAT Suite Question Bank (Reading & Writing)',
            url: 'https://satsuitequestionbank.collegeboard.org/',
            source: 'College Board',
            description: 'Filter thousands of official reading passages by Information and Ideas, Craft and Structure, and Expression of Ideas.',
          },
          {
            id: 'ext-sat-rw-bluebook',
            title: 'Official Bluebook App',
            url: 'https://bluebook.collegeboard.org/',
            source: 'College Board',
            description: 'Practice adaptive test reading modules with live timer and highlight annotations.',
          },
        ],
      },
      {
        id: 'sat-rw-craft-structure',
        name: 'Craft and Structure: Words in Context & Purpose',
        subtopics: [
          'Words in context: high-frequency vocabulary and contextual clues',
          'Text structure and purpose: identifying main rhetorical goal',
          'Cross-text connections: comparing perspective in dual passages',
        ],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [
          {
            id: 'ext-sat-rw-khan-craft',
            title: 'Khan Academy - Official Digital SAT Craft and Structure',
            url: 'https://www.khanacademy.org/test-prep/v2-sat-prep/x0fcc98a58ba3be7a:craft-and-structure-core-skills',
            source: 'Khan Academy',
            description: 'Learn targeted strategies for vocabulary in context and evaluating text structure.',
          },
        ],
      },
      {
        id: 'sat-rw-grammar-conventions',
        name: 'Standard English Conventions & Transitions',
        subtopics: [
          'Sentence boundaries: run-ons, comma splices, fragments, and semicolons',
          'Subject-verb and pronoun-antecedent agreement',
          'Modifier placement (dangling modifiers)',
          'Logical transition words (however, furthermore, therefore, consequently)',
          'Rhetorical synthesis: bullet-point synthesis questions',
        ],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [
          {
            id: 'ext-sat-rw-khan-conventions',
            title: 'Khan Academy - Official Standard English Conventions',
            url: 'https://www.khanacademy.org/test-prep/v2-sat-prep/x0fcc98a58ba3be7a:standard-english-conventions-core-skills',
            source: 'Khan Academy',
            description: 'Master all grammar questions, punctuation rules, and transitions tested on the Digital SAT.',
          },
        ],
      },
      {
        id: 'sat-rw-information-ideas',
        name: 'Information and Ideas: Central Ideas & Details',
        subtopics: [
          'Central ideas and key details in scientific and literary prose',
          'Inferences and drawing logical conclusions from passages',
          'Textual evidence and quantitative evidence (graphs, charts, data tables)',
        ],
        isHlOnly: false,
        youtubeResources: [],
        pastPapers: [],
        externalResources: [
          {
            id: 'ext-sat-rw-khan-info',
            title: 'Khan Academy - Official Digital SAT Information and Ideas',
            url: 'https://www.khanacademy.org/test-prep/v2-sat-prep/x0fcc98a58ba3be7a:information-and-ideas-core-skills',
            source: 'Khan Academy',
            description: 'Targeted practice for understanding complex academic texts and scientific data tables.',
          },
        ],
      },
    ],
  },
];

// ============================================================================
// Helper query functions
// ============================================================================

export const getSyllabusById = (id: string): SubjectSyllabus | undefined => {
  return SYLLABUS_DATA.find((s) => s.id === id);
};

export const getSyllabusBySubject = (subject: string): SubjectSyllabus | undefined => {
  return SYLLABUS_DATA.find((s) => s.subject.toLowerCase() === subject.toLowerCase());
};

export const getSyllabiByCurriculum = (curriculum: Curriculum): SubjectSyllabus[] => {
  return SYLLABUS_DATA.filter((s) => s.curriculum === curriculum);
};

export const getAllCurricula = (): Curriculum[] => {
  return Array.from(new Set(SYLLABUS_DATA.map((s) => s.curriculum)));
};
